import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import { GlassFilter } from '@/components/GlassFilter';
import './globals.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

/**
 * 只放整份文档都用得上的东西：html/body、字体、全局 css、全局 SVG 滤镜。
 *
 * 页面的外壳（侧边栏、内容区尺寸、留白……）各页自己带：auth 那组在 `(auth)/layout.tsx`，
 * 首页只有一页、壳子就直接写在 `page.tsx` 里。这里不要加。body 的 `mx-auto max-w-400` 是全局的
 * 画布宽度，auth 那边靠 `flex-1` 居中也是接着这层 flex column 的，所以留在根上。
 */
export default function RootLayout({ children }: LayoutProps<'/'>) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}>
      <body className="mx-auto flex min-h-full max-w-400 flex-col">
        {/* liquid glass 的折射滤镜，全局一份，见 components/GlassFilter.tsx */}
        <GlassFilter />
        {children}
      </body>
    </html>
  );
}
