// Aggregates every drizzle schema file so app code and drizzle-kit have a
// single entry point. Add new schema files here as they appear:
//   export * from "./posts";
//
// Note: better-auth.ts is generated by `pnpm auth:generate` — never edit it by
// hand, and keep its exports reachable through this file.
export * from './better-auth';
